name: reddit-sentiment-and-trend-analysis
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - annotated-types=0.6.0
  - arrow-cpp=17.0.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.27
  - aws-c-io=0.13.11
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - bertopic=0.16.2
  - boost-cpp=1.82.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - catalogue=2.0.10
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - confection=0.1.4
  - cpython=3.10.16
  - cymem=2.0.6
  - cython=0.29.37
  - cython-blis=0.7.9
  - datasets=2.14.4
  - dill=0.3.7
  - filelock=3.16.1
  - freetype=2.10.4
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h2=4.1.0
  - hdbscan=0.8.39
  - hpack=4.0.0
  - huggingface_hub=0.26.5
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.20.1
  - langcodes=3.3.0
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.11.1
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libhwloc=2.11.2
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.28
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libtorch=2.4.1
  - libuuid=1.41.5
  - libuv=1.49.2
  - libwebp-base=1.5.0
  - libxml2=2.13.5
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - mdurl=0.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - murmurhash=1.0.7
  - ncurses=6.5
  - networkx=3.4.2
  - nltk=3.9.1
  - nomkl=1.0
  - numba=0.60.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - orc=2.0.1
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=24.2
  - plotly=5.24.1
  - praw=7.7.1
  - prawcore=2.4.0
  - preshed=3.0.6
  - propcache=0.2.1
  - pyarrow=17.0.0
  - pycparser=2.22
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.15.1
  - pynndescent=0.5.13
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-dotenv=0.21.0
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.4.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - rich=13.9.4
  - s2n=1.3.30
  - safetensors=0.4.5
  - scikit-learn=1.6.0
  - scipy=1.14.1
  - sentence-transformers=3.3.1
  - setuptools=75.1.0
  - shellingham=1.5.0
  - six=1.17.0
  - sleef=3.7
  - smart_open=5.2.1
  - snappy=1.2.1
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.45.3
  - srsly=2.4.8
  - sympy=1.13.3
  - tbb=2022.0.0
  - tenacity=9.0.0
  - thinc=8.2.2
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tokenizers=0.21.0
  - tqdm=4.67.1
  - transformers=4.47.1
  - typer=0.9.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - umap-learn=0.5.7
  - update_checker=0.18.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wasabi=0.9.1
  - weasel=0.3.4
  - websocket-client=1.8.0
  - wheel=0.44.0
  - xxhash=0.8.2
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.3
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - en-core-web-sm==3.7.1
      - fonttools==4.55.3
      - kiwisolver==1.4.8
      - matplotlib==3.10.0
      - pyparsing==3.2.0
