name: realtime-dashboard
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - ld_impl_linux-64=2.43
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.3
  - libmpdec=4.0.0
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.0
  - pip=24.3.1
  - praw=7.7.1
  - prawcore=2.4.0
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.13.1
  - python-dotenv=0.21.0
  - python_abi=3.13
  - readline=8.2
  - requests=2.32.3
  - tk=8.6.13
  - tzdata=2024b
  - update_checker=0.18.0
  - urllib3=2.3.0
  - websocket-client=1.8.0
  - zstandard=0.23.0
  - zstd=1.5.6
